id: P7F798A4A
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: fr
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    cdfe7db090c84218965e3ff97d5d6f00:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    4d1c04f0c0a443179e8795126542070f:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    a95f5173f90040589c0d00697d1408b9:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    944482c601ea4839baa51c8ba76351fd:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    81f38d71939c4518a83ff33c78dc33d1:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.800629'
last_modified_at: '2022-03-01T02:52:02.800631'
